#!/bin/bash
#To collect CPU, Memory and Disk Usage from Multiple Servers
#Author : Haalith
#Desingnation : Hostname, Date & Time,  CPU%, Mem%, Disk%

HOSTNAME=$(hostname)
DATET=$(date "+%Y-%m-%d %H:%M:%S")
CPUSAGE=$(top -b -n 1 -d1 | grep "Cpu(s)" | awk '{print $2}' | awk -F. '{print $1}'
MEMUSAGE=$(free |grep Mem | awk '{print $3/$2 * 100.0}')
DISKUSAGE=$(df -p |column -t |awk '{print $5}' | tail -n 1 | sed 's/%//g')

echo 'Hostname, Date&Time, CPUi(%), Mem(%), Disk(%)'  >> /opt/usagereport
echo "$HOSTNAME, $DATET, $CPUSAGE, $MEMUSAGE, $DISKUSAGE" >> /opt/usagereport
